### ISSUE TITLE
When referencing two data structures, only one is imported in XSD

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/dataspecer#711] opened 2024-09-26 14:50 UTC
[This specification](https://xn--slovnk-7va.gov.cz/generujeme/editor?data-specification=https%3A%2F%2Fofn.gov.cz%2Fdata-specification%2F921efca8-2017-4881-914f-b46137fc11e4&data-psm-schema=https%3A%2F%2Fofn.gov.cz%2Fschema%2F1727173003869-aa57-bd0b-8a42) re-uses two data structures - person and physical person. However, in the resulting XSD, only one of them is imported.

**Comment by sstenchlak** [comment] 2024-09-26 19:13
The issue is that imported data structures share the same namespace and namespace prefix. If you make them different, it should work. I am not sure whether this is legal and hence bug in Dataspecer, or not.

**Comment by jakubklimek** [comment] 2024-09-26 19:31
Actually, I originally thought the same thing and had the mention of the namespace in the issue. But it is not the cause, as when I change one of the namespaces (at least their IRIs, I did not try the prefixes), the bug remains.
In any case, in XML, it is legal (the designer needs to be aware of potential conflicts), hence a bug in Dataspecer.

**Comment by sstenchlak** [comment] 2024-10-01 13:15
<img width="962" alt="image" src="https://github.com/user-attachments/assets/0c523c5c-0069-4f8a-aa0d-7ea14bba2c8a">

Ok, you can have two different imports with the same namespace and prefix, but you cannot have two different imports with the same prefix but different namespace.

Also, according to the current behavior, prefixes are being assigned to the structure itself instead of being assigned to the referenced structure within another structure. This can lead to unsolvable conflicts. The original prefix should serve only as a recommendation.

**Comment by jakubklimek** [comment] 2024-10-01 13:20
> Ok, you can have two different imports with the same namespace and prefix, but you cannot have two different imports with the same prefix but different namespace.

Yes, of course. The ID of the namespace is its IRI. The prefix is only a short name for a namespace IRI, so you cannot have one name for two things.

> Also, according to the current behavior, prefixes are being assigned to the structure itself instead of being assigned to the referenced structure within another structure. This can lead to unsolvable conflicts. The original prefix should serve only as a recommendation.

Yes, the original prefix is to be used in the original XSD, for the referencing XSD it is only a recommendation. Should be fine if the namespaces are same, needs to be different if they are different.

**Closed** 2024-10-01 13:37 UTC
Labels: bug, asap
